# Modern Docker Compose - no version needed
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        # Changed this line to use the service name 'backend' and its internal port
        NEXT_PUBLIC_BACKEND_URL: "http://backend:8005" # This is the key change!
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: python-backend
    ports:
     - "8005:8005" # Keep this if you want to access the backend directly from your host for debugging/testing
    volumes:
      - /mnt/drive/Media:/app/downloads_root # Ensure this is where your app expects to write
    environment:
      # Ensure this matches the volume mount path inside the container
      - BASE_DOWNLOAD_DIR_ENV=/app/downloads_root
      # GPU-related environment variables
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    # GPU access - use runtime method (more reliable)
    runtime: nvidia
    restart: unless-stopped
    networks:
      - app-network

# Create a custom network for better container communication
networks:
  app-network:
    driver: bridge
